### ISSUE TITLE
Billing framework via Stripe

### ISSUE THREAD

**Issue by dlobo** [glific/glific#1334]
Lets automate our billing process and integrate stripe so we avoid chasing NGOs to pay their bills! This also will help us enforce the tiered policy and tie stats into the system quite nicely

**Comment by pankaj-ag** [comment]
From @mdshamoon 

Need the following API's to complete the stripe integration:

- [ ] An API endpoint to check whether the organization is already subscribed to a plan
- [ ] API endpoint to get customer and their subscription plan details
- [ ] Handling 3d secure support if needed (this needs an additional confirmation from the frontend) https://stripe.com/docs/billing/subscriptions/metered#manage-payment-authentication
- [ ] If needed, an unsubscribe option

**Comment by mdshamoon** [comment]
Encountered these issues while testing

1. Getting error using this test card 4000053560000011 (This card requires authentication on all transactions, regardless of how you set it up. You can only use this card for INR payments.) 

This breaks the backend instead of sending an error message

I have already tested it with most of the test cards. You can use this link to get more card numbers to test:
https://stripe.com/docs/testing

2. Subscription id is not created in case of 3d secure payments. We can't check if the organisation is already subscribed or not.

**Comment by mdshamoon** [comment]
@pankaj-ag further improvements needed in stripe

1. Send specific error messages for various card declined scenarios. For now we are sending this default error message

![image](https://user-images.githubusercontent.com/32592458/114666846-612e4700-9d1c-11eb-8ba0-2706da130555.png)

2. In 3D secure payment if we fail the authentication then also a subscription is created on the stripe end. We need to stop or remove that subscription in that case.

**Comment by mdshamoon** [comment]
Also can we add an endpint to get customer portal session https://stripe.com/docs/billing/subscriptions/integrating-customer-portal#redirect.

This way user can see their plan and usage in the stripe hosted customer portal.

**Comment by dlobo** [comment]
I've moved the last two comments into its own issue. We'll tackle this in v1.4.1 or v1.5
