### ISSUE TITLE
Multiple tag assignment to a message in single API call

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific#186]
**Is your feature request related to a problem? Please describe.**
Right now, we have a GQL mutation (`createMessageTag`) to assign one tag with a message. However, the UI functionality is flexible to assign multiple tags at once. To support this, multiple API calls have to be made for each tag assignment with the message.

**Describe the solution you'd like**
A solution for this can be another mutation, that accepts an array of tagIds that need to be assigned with a message. 

**Additional context**
Since users can also unselect a previously assigned tag, it'll also be better if the query unassign the message tags that are not present in the mutation input. This will help avoiding additional API calls for `deleteMessageTag`.

For reference, here's a screenshot of the tag assignment screen for a message:
![image](https://user-images.githubusercontent.com/12053186/85863932-76fc6b00-b7e1-11ea-9084-fe4b38fe599e.png)

**Comment by dlobo** [comment]
I've resolved this issue and merged the PR with master

However, I've not implemented the delete aspect of things primarily since there are a few tags that the user cannot add or delete like New Contact / Read but not replied and a bunch of automation tags. So a blanket removal of those would be dangerous

let address the "what tags to remove" and how the frontend can let us know explicitly in a future issues

ideally the UI will send us the foll:

message_id
add_tag_ids
remove_tag_ids

so the contract is clear and explicit. 

Also if any fail, we ignore failures but only let the caller know which ones succeeded
