### ISSUE TITLE
Message not sent to Glific and BOT stuck

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2102]
Mukkamaar reported the issue. Contact sent a message which was not received at Glific.
Tested the wait for a response is not returning a valid response.
Contact name - Saloni Gupta
Flow name - Non-physical day 10
When - 1st Mar 2022 @ 22:45

<img width="1146" alt="Screenshot 2022-03-02 at 6 29 15 PM" src="https://user-images.githubusercontent.com/16541548/156368964-0989262a-2a2c-453e-86a9-05b5f12d47c8.png">

<img width="639" alt="Screenshot 2022-03-02 at 6 47 46 PM" src="https://user-images.githubusercontent.com/16541548/156369579-8080de5c-7ae7-47f5-93b3-c3692fa974ba.png">

**Comment by mdshamoon** [comment]
@mohitsharma-22 I checked the issue and the flow stopped for this user because the flow moved forward after 3 hours and stopped after sending five same audio messages.
<img width="974" alt="image" src="https://user-images.githubusercontent.com/32592458/156502416-3bb5b13c-b8a9-42de-a7ec-3fc596983cf3.png">


In case of simulator it moved to the next message but the message is not updated on the simulator maybe due to a connection error. If you will look in the chats it has moved to the next node
<img width="991" alt="image" src="https://user-images.githubusercontent.com/32592458/156502723-828623c1-7000-4728-b00b-fcc9480fef8c.png">

Let me know if you have any questions

**Comment by mohitsharma-22** [comment]
Thanks, @mdshamoon Actually contact replied to the message, which was not captured in the chat. Please check the screenshot.
![image0](https://user-images.githubusercontent.com/16541548/156507263-b1a4f17a-d8d7-4ee1-8972-bf2fecc31516.jpg)


Also, Can you please suggest what is wrong in the text Reacting is imp!, why it is not working as a valid response.

**Comment by mdshamoon** [comment]
@pankaj-ag the above shown screenshot message is not received on the system. Can you please help in checking this?

**Comment by pankaj-ag** [comment]
@mohitsharma-22 we are not able to replicate it.Currently we are just Guessing. Can we please keep a track of this issue and let us know if this happens again. 

For now we are putting this on hold.

**Comment by dlobo** [comment]
could not replicate
