### ISSUE TITLE
Flows are getting killed in between

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2211]
Issue reported by Mukkamar.
<img width="576" alt="Screenshot 2022-04-19 at 1 48 14 PM" src="https://user-images.githubusercontent.com/16541548/163958141-c6ae0d4d-ce7c-4d61-8ec1-96eed2538770.png">

<img width="1220" alt="Screenshot 2022-04-19 at 1 47 43 PM" src="https://user-images.githubusercontent.com/16541548/163958185-28de95eb-4f8b-4ebc-8c3c-a8e1bc75ed9f.png">

<img width="567" alt="Screenshot 2022-04-19 at 1 49 07 PM" src="https://user-images.githubusercontent.com/16541548/163958218-49f2f8ee-e1f0-47cf-a136-d725837b9c01.png">

<img width="560" alt="Screenshot 2022-04-19 at 1 49 31 PM" src="https://user-images.githubusercontent.com/16541548/163958239-2b4dd933-8519-4a96-9ae9-3133528b646e.png">

**Comment by mohitsharma-22** [comment]
Steps to replciate:
1. Start Help Flow.
2. Select English from the interactive message.
3. It should send the message " Type your password" to start your next level. But nothing happens after that.

**Comment by AkhileshNegi** [comment]
@mohitsharma-22 In this case the option `change language` in the interactive message button is also a flow keyword.
Therefore instead of going into `enter another flow` node, it starts the language change flow

In this case for both `enter another flow` node and `keyword ` flow  is same flow `Change in Language Selection` which is why there is confusion

Steps to replicate:
1. Send a interactive message from chat screen with name `Hello my friend`
2. Choose option `Change language`
3. Flow `Change in Language Selection` is triggered because of keyword

To prevent this case the main flow `HELP FLOW` should have `ignore keywords` checked or remove `Change language` as a keyword from `Change in Language Selection` flow

**Comment by Ranjana-G** [comment]
@mohitsharma-22 , @AkhileshNegi , Can we avoid getting to this point ? Does the UI check need to be tightened or do we need to do a back-end data scrub for older data or both ?

**Comment by mohitsharma-22** [comment]
@mdshamoon @abhi1203 Had a talk with @Ranjana-G. She is suggesting can put a check while saving the interactive message, if the button text matches a keyword, then give an alert. Just checking if that is possible?

**Comment by AkhileshNegi** [comment]
It can be done while creating the interactive template but there is always a possibility that we create a template and at the point of creation the button text does not match any of the flow keywords.
The issue is once the template is created then a flow can be created at a later point in time with the keyword same as button text.
@abhi1203 We can add a warning text perhaps that kindly check if the button text does not match with the flow keyword always.
Let me know your thoughts here

**Comment by Ranjana-G** [comment]
@AkhileshNegi , We will have to likewise ensure a keyword doesn't match a button selection. 

Ideally a button or list selection should be treated as more than just text response and possibly have priority. But that would need design.

**Comment by mohitsharma-22** [comment]
The root cause identified in this issue was the button response is the same as another flow keyword, which causes killing the flow. Closing this task for now.
