### ISSUE TITLE
Flows getting killed without any new event started.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific#2224]
1. Started flow 03 - NP2
2. Responded to 4 questions.
3. The flow was killed at 5:00 PM. Not able to find any keyword in the responses or other flow started.
4. Created a test trigger to investigate, if that is a reason. The trigger fired at 5:07 PM. But the flow was killed at 5:00 PM.

This is a very frequent issue in Mukkamaar. Can you please check what causes these flows to be killed?
<img width="557" alt="Screenshot 2022-04-25 at 5 07 07 PM" src="https://user-images.githubusercontent.com/16541548/165088822-032e6fa1-ef14-4c82-a8d7-0f54462ee8a8.png">

<img width="1206" alt="Screenshot 2022-04-25 at 5 57 57 PM" src="https://user-images.githubusercontent.com/16541548/165089009-14638bad-effc-4377-9fc9-d016cfd39bec.png">

**Comment by mohitsharma-22** [comment]
Sharing other screenshots for flow being killed issue

![2022-04-19](https://user-images.githubusercontent.com/16541548/165229056-f4e3fb89-f83c-457b-b502-2610a44f5b08.png)

![2022-04-19_2](https://user-images.githubusercontent.com/16541548/165229066-27628a16-7c66-4f2c-b95d-e18c20d648fd.png)

**Comment by mdshamoon** [comment]
I have checked the three cases and the flow has not been killed in either of the them. 

For Anita and mundaajay072 the flow ended after a wait for response node where the user didn't answer. 
Since the wait for response node has the option selected `continue if there is no response after 3 hours` and because no node is connected to the `no response` category, the flow ended.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/32592458/165238072-d4e01ce4-37c7-4ae3-a282-8c6735350dc4.png">


For Ishita the flow studentrank flow started and completed within 1 minute since it had only one node.

**Comment by mdshamoon** [comment]
@pankaj-ag @AkhileshNegi @dlobo Case of Anita with contact id: 28631. 
The flow has not been killed but the contact history still shows all contact flows are ended. I looked through the code and can't seem to find any possible way from where this line has been added after a flow starts. Need your help in debugging this further.

<img width="557" alt="Screenshot 2022-04-25 at 5 07 07 PM" src="https://user-images.githubusercontent.com/16541548/165088822-032e6fa1-ef14-4c82-a8d7-0f54462ee8a8.png">
