### ISSUE TITLE
Bug in optin API - phone number shows in Gupshup but not Glific user list

### ISSUE THREAD

**Issue by Ranjana-G** [glific/glific#2226]
Reported by VOPA. Akhilesh was on call. 

Optin API is called and phone number is present in Gupshup but not glific. 

A related issue is that the standard optin message is also displayed which is redundant. Ideally after the optin API bug is fixed. The user should not see the standard optin message.

**Comment by mdshamoon** [comment]
### Optin API is called and phone number is present in Gupshup but not glific.
Please share an example of the contact where this case happened so i can have a look


### A related issue is that the standard optin message is also displayed which is redundant. Ideally after the optin API bug is fixed. The user should not see the standard optin message.
This was happening because the optin flow had the keywords `hi, hello` in them which triggers the optin flow.

**Comment by Ranjana-G** [comment]
@mdshamoon , Based on the call we had with Akhilesh the issue is clear. and you believe you have a fix for it - The optin status was not should correctly in the conversation page although details page showed it. You are on track for deployment this evening. Please update this issue as soon as deployment is complete so I get a notification.

**Comment by mdshamoon** [comment]
@Ranjana-G the fix is deployed. Please test it at your end and let me know if you face any issues.

**Comment by Ranjana-G** [comment]
Looks great ! Closing the issue.
