### ISSUE TITLE
Implement new api endpoint for validations during registration process

### ISSUE THREAD

**Issue by kurund** [glific/glific#263]
**Is your feature request related to a problem? Please describe.**
* We need an API endpoint to validate the user

**Describe the solution you'd like**
* Create API endpoint that we do following
* Check if the phone number has opted in
* Check if the user exists with the entered phone number

**Comment by kurund** [comment]
Any update on this?

**Comment by dlobo** [comment]
I think we can add these api's for v0.2, but we'll need to do some research and reading up on best security practices on how to do this.

These are unauthenticated rest APIs. Implementing them, means any attacker could also use them to try and find numbers in our DB. Since I suspect that we'll have far fewer users etc, creating a user, giving them multiple potential errors (without being specific) and adding a random amount of time (to make it non-deterministic) should suffice

The admin should be able to see all the users from their screen, so do we really need this (and the associated security issues?)

**Comment by dlobo** [comment]
Spoke to kurund about this. We'll keep the flow as described below

1. person opts-in to gupshup
2. person comes to create account page and adds info
3. Frontend sends an otp request to backend
4. backend says "sent, or failed"
  if failed, frotnend displays error message
  if success, user enters otp
5. frontend makes create_user request
6. backend returns success or failure
7. on all failures, vague message is displayed
