### ISSUE TITLE
Name is not saved when contact is opted in

### ISSUE THREAD

**Issue by kurund** [glific/glific#291]
**Describe the bug**
* Earlier name was being saved in the backend when a user opts-in

**To Reproduce**
1. Reset the DB
2. Send a message to Gupshup for opt-in
3. Register to Glific
4. You will see the number for the contact as the name is not saved in DB.

**Expected behavior**
* Name should be recorded like before

**Comment by pankaj-ag** [comment]
@kurund I just checked, Gupshup does not send the contact name with Opted in the message. 
```
%{
		"app" => "TidesTestApi", 
			"payload" => %{
			"phone" => "919917443994", 
			"type" => "opted-in"
		}, 
	
		"timestamp" => 1595823744547, 
		"type" => "user-event", 
		"version" => 2
	}
```

We will get the name when contact starts the conversation with Glific NPO and then it gets saved to the DB. 

I think earlier we were using the session message flow only not the opted in, that's why it was showing the name.

**Comment by pankaj-ag** [comment]
Closing this now. Please reopen in case any work is required on this.

**Comment by kurund** [comment]
@pankaj-ag Make sense. I have also confirmed that the name is set once we send the session message.
