### ISSUE TITLE
Common Webhook: Client file issue

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2910]
**Describe the bug**
In Glific, we have support for common webhook which is used to implement a few common webhooks across organizations. With current implementation in `lib/glific/clients.ex` file we check if the organization module exists or not. If exist we redirect this to the client file else we use common webhook.

The issue arises if the organization with a client file wants to use common webhook functionality.

**Expected behavior**
Move to common webhook if the client file does not have support to process current function

**Comment by dlobo** [comment]
@AkhileshNegi for orgs that want to use functionality in a common file, cant they just say:

(in the plugins array)

webhook: Glific.Clients.CommonWebhook

**Comment by mahajantejas** [comment]
Hi @AkhileshNegi @dlobo re-opening this. 

it was categorized high priority in March, and it has resurfaced again: https://discord.com/channels/717975833226248303/1243530745918787604 

Since we are introducing more integrations, it makes sense to have generic webhook functions available to all orgs in one shot, instead of needing to add separately for each of them after making a generic build.
