### ISSUE TITLE
Internal Dashboard: Sending emails

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#2967]
**Describe the solution you'd like**
Sending weekly report of internal dashboard

**Comment by Darshan2003** [comment]
Tried one possible approach to use `Hound` UI testing library to take screenshot of dashboard. But there are some security concerns with this approach and also it increases load on server.

Another approach could be to create an HTML template of the dashboard which would be populated with data and that rendered HTML string as mail to organizations

**Comment by aravind-glific** [comment]
Instead of weekly, a **monthly** email would be the way to go. Weekly could be a bit too much & chances of keeping it unread is on the higher side. Just a thought.

These are some of the high-level pointers that could be part of the recurring email :
1. **Metrics**
- Monthly Conversations
- Monthly Contacts :  Valid, Opted in, Opted out, Non-opted in, Invalid
- Monthly Inbound & Outbound

2. **URLs**
- Internal Dashboard URL
- DataStudio Dashboard URL(since most NGOs never regularly check the data studio dashboard)

**Comment by mahajantejas** [comment]
What is the logic behind keeping it monthly? 
Do we have any user inputs on this? 

In my opinion, we should try to get some feedback on the frequency after trying, and in my opinion we should start off weekly or once in 2 weeks. 

@aravind-glific @mdshamoon 

From my experience of using the platform, Metrics that I'd have liked to see are 

1. New Contacts opted in 
2. No of contacts active in the time span (initiated or responded to a conversation) 
3. No of messages sent and received

**Comment by aravind-glific** [comment]
@mahajantejas The thought process was that getting 4 quick reports in a month might be a little extra. Chances for NGOs to start ignoring it after some time seems to be higher. 

- Making it monthly (or even fortnightly for that matter) keeps the email more comprehensive & the action items/ analysis to be done over it could be higher.
- It also makes trend identification easier & enables tracking of monthly variation in various metrics easier. Having a weekly report might not let them/ help them track things on a monthly basis since it requires more effort to compile & analyse.
- In general, monthly updates could easily be tagged to long-term goals  & strategic decision making.
- Also, a slightly behavioural aspect, when you get a monthly wrap-up you tend to find it more valuable/ informative compared to a weekly report which lacks rarity
- The above given reasons are more intuition driven than evidence. We can definitely try capturing some input from NGOs as well before taking a final call.
- The metrics you suggested could be part of the email (1 & 3 was already mentioned, 2 could be added as well)
