### ISSUE TITLE
Automated Flow Tester : Warning  Flow in Trigger doesn't start with HSM

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific#3240]
Flow not getting triggered - [Reap Benefit](https://discord.com/channels/717975833226248303/1164914298561237034)

The flow was not getting triggered since the flow used in Trigger didn't start with HSM template.
Solution - Make sure that the first send message node in the flow used in Triggers must be an HSM template. This check should be done whenever a Trigger is created & a warning needs to be shown if the first node is not template. The warning will not be present for flows where no 'Send message' nodes are involved.

**Comment by aravind-glific** [comment]
@AmishaBisht It should check and give a warning if :
1. First 'Send message' node is not a template message. Send message node includes interactive message as well.
2. If there is 'Enter another flow' before any 'Send message' node, it should apply the same logic to the flow inside 'Enter another flow'

**Comment by mahajantejas** [comment]
Unexpected behaviour: 
1. If the first message is not HSM template in the flow being triggered, It is showing an error and not allowing to publish the trigger. Expected behavior : show a warning only 
2. If the first node is "split by" followed by HSM templates, in the flow being triggered it showing a error and not allowing trigger to be published. Expected behvior: no need to show warning, allow the flow to be published - bug filed here https://github.com/glific/glific/issues/3267
3. If the first node is "add label", followed by "split by", followed by non hsm template, the trigger is getting published without any warning or error. Expected behavior: show a warning only
