### ISSUE TITLE
Export translations CSV to have node UUIDs instead of action UUIDs

### ISSUE THREAD

**Issue by mahajantejas** [glific/glific#3446]
the exported CSVs are not in order of the flow, therefore it is difficult to match the strings in the sheet to the nodes, 

having node UUIDs in the sheet can make it easier to match.

At present the exported CSVs contain action UUIDs, and these are mostly hidden on the glific's flow editor.

Steps to replicate: 
1. Go to a flow: https://prod.glific.com/flow/configure/35dfed83-17c7-4560-8f71-00b9212d4fa2
2. Export without auto translations 
3. Observe that the exported CSVs have a action UUID which cannot be matched on any node in the flow.

<img width="902" alt="Screenshot 2024-03-19 at 9 06 46 AM" src="https://github.com/glific/glific/assets/141305477/f45f818e-7393-4f3c-b1a7-a1a6e3090af4">

**Comment by AmishaBisht** [comment]
@mahajantejas, here in the CSV, we can't remove the action UUID because:
1. If we add two nodes in a single node, each node will have two different action UUIDs and a single node UUID. Though such cases are rare, if even a single case exists, this approach would fail.
2. The flow editor is more convenient for action UUIDs.
However, what we can do is also show the node UUID along with the action UUID in the last column, labeled as 'node UUID'

**Comment by mahajantejas** [comment]
@AmishaBisht then go with the option of showing node UUIDs as well. (the last line mentioned by you)
