### ISSUE TITLE
NGOs receiving obscene media & messages on chatbot

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific#3729]
Though this issue isn't a bug, adding it in this category.

We have 2 organizations (Nayi disha & Sight savers) who recently reported increase in the number of spam messages, especially obscene media & messages. This is one issue which is troubling both the organizations and they requested us for an solution to avoid it (or atleast blur such images). Sight savers also mentioned that they would delete their chatbot with Glific if the issue doesn't get resolved.

One common thing in both these orgs is Social media (facebook) is one of their common outreach channels. As per their program, their audience will be found on social media- so we can't them to restrict that communication channel aswell.

We reached out to Suraj from Gupshup asking if they know of any solution as they work with orgs who has large numbers. But even they didn't share any solution which can solve problem at scale.

As more organizations can face similar problem in future, it is important for us to find solutions which can mitigate/ solve the problem.

@madclaws

**Comment by madclaws** [comment]
Some actionable items we could do or explore here are,
- Figure out if we could validating text messages for obscenity and remove those messages from the platform
- Blocking the contacts based on the above validation
- For other media files we could use ML to verify them in background and block the contacts.

**Comment by AkhileshNegi** [comment]
@KrishnaDwibhashi2 We need more details from the NGO partner about the steps that need to be taken and the typical pattern of obscene media or messages being sent. Since this will involve an architectural change—checking every incoming message for such content—it could put a significant load on the system. Understanding the pattern of these messages and the proposed course of action would be really helpful.

Blocking contacts right away isn't a straightforward solution because once a contact is blocked, we can't check their chat in Glific, and there's no clear way to detect if a newly blocked contact. Adding a notification might help, but we need the NGO's perspective on this to figure out the best approach.

**Comment by KrishnaDwibhashi2** [comment]
FYI- Waiting for Nayi disha to get back. Followed up again today
