### ISSUE TITLE
Contact not being able to optin again.

### ISSUE THREAD

**Issue by akanshaaa19** [glific/glific#3912]
**Describe the bug**

**To Reproduce**
1. Go to search.glific.com instanct
2. Optout from the bot
3. then send optin keyword "chatwithsearch"
4. The flow will fail and in notification you will see this error

but the same steps in prod is working fine even if status is invalid

<img width="1159" alt="image" src="https://github.com/user-attachments/assets/fa7bf8c2-9070-4a1f-9347-bd50567aca7e">

**Comment by AmishaBisht** [comment]
The issue was that the opt-in flow was not starting for the user after they opted out. This happened because there was no default opt-in flow selected. Additionally, we also trigger the opt-in flow without explicitly setting it up by creating an opt-in flow with the keyword "optin." If there is any flow with the keyword "optin," it will be triggered, even if no default opt-in flow is selected. In this particular case, neither of these conditions were met — there was neither a default flow selected nor a flow with the "optin" keyword.
